version = 2

[debug]
  address = ""
  format = ""
  gid = 0
  # Can be changed to "debug" when more detailed logging is desired
  level = "info"
  uid = 0

[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    stream_server_address = "127.0.0.1"
    max_container_log_line_size = 262144
    sandbox_image = "registry.k8s.io/pause:3.7"

   [plugins."io.containerd.grpc.v1.cri".cni]
      bin_dir = "/opt/cni/bin"
      conf_dir = "/etc/cni/net.d"

  [plugins."io.containerd.grpc.v1.cri".containerd]
    default_runtime_name = "runc"

  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
    runtime_type = "io.containerd.runc.v2"

  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true
      
  [plugins."io.containerd.internal.v1.opt"]
    path = "/var/lib/containerd/opt"
