- name: "Install VMs"
  hosts: all
  serial: 1
  become: true
  gather_facts: no
  vars:
   vm:
    hostname:
      "{{ inventory_hostname_short }}"
    ip_address:
      "{{ ip_address }}"
   ansible_become_hash: "$6$Zm1jb3X4YhOKXK.G$CpKtWuFeBvr/YpzY68O4OsawwHmfoq/rZMiB7Fk07mthODithlwkPruKobTcZjxuTP2NQ2PM.KEFilIoDVmK80"

  pre_tasks:
  - name: "Load the vm template"
    include_vars: debian_vm_template.yaml

  - name: "display cloud_localds"
    debug:
      msg: 
      - "cloud_localds: {{ cloud_localds }}"

  - name: "download install image"
    delegate_to: localhost
    ansible.builtin.get_url:
      url:  "{{ qemu_img.url }}"
      dest: "{{ qemu_img.src }}"
      mode: "0444"
      force: no

  tasks:
  - name: "Install {{ inventory_hostname_short }}"
    include_role:
      name: stafwag.virt_install_vm
      apply:
        delegate_to: localhost
