- name: Install provisioners
  hosts: localhost
  become: false
  gather_facts: yes
  environment:
    KUBECONFIG: "{{ playbook_dir }}/kubernetes/admin.conf"
    PATH: "{{ ansible_env.PATH }}:{{ playbook_dir }}/bin"

  tasks:
  - name: Install storage provisioner
    include_role:
      name: install_nfs_provisioner
